### PR TITLE
[buildmgr] Add Star-MC1, Cortex-M55 and Cortex-M85 to IAR Compiler configuration.

### PR DESCRIPTION
**Pull request by grasci-arm**

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
@tarek-bochkati, please review this.

**Comment by tarek-bochkati** [comment]
LGTM, but IMO we need to rename this cmake file to the latest IAR version supporting Cortex-M85 (9.30.1 or later)

@mario-pi

**Comment by JonatanAntoni** [comment]
@tarek-bochkati, good catch. What versions of compilers shall be supported? Do we need multiple versions then?
cc @brondani

**Comment by tarek-bochkati** [comment]
checking the history of GCC and ACx cmake files, I found that these files have been renamed to mirror the latest toolchain available versions.

also, I have checked that:
* **Cortex-M55** is supported since **IAR 9.20.4**
* **Cortex-M55** is supported since **IAR 9.30.1**

latest **IAR 9.32.1** is just adding Cortex-R82 support

Based on this, I recommend switching the latest 9.32.1

cc: @mario-pi

**Comment by mario-pi** [comment]
@grasci-arm @JonatanAntoni thanks for providing this. As @tarek-bochkati noted, the file should be renamed to match the version of the IAR toolchain that supports the new cores. @tarek-bochkati should there be only one file for the latest greatest supported version, or is it possible to address multiple versions of the same toolchain? We are working to be able to test and provide the cmake files for IAR ourselves but unfortunately not up to speed yet.

**Comment by brondani** [comment]
> @brondani, any thoughts about this? What happens with users of version 8 once we rename the file?

I wouldn't start shipping a separate file for every supported version due to the significant effort it could demand when it scales up. I believe we need a better strategy for toolchains configuration as commented [here](https://github.com/Open-CMSIS-Pack/devtools/issues/68#issuecomment-989938770).
For the time being I would suggest to ship only one file for the latest supported version.
In the current setup users need to manually update their configuration when [installing the tools](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md) regardless of the toolchain version.

**Review by brondani — APPROVED** [review]

**Pull request merged**
