### PR TITLE
Proposal: CPRJ/MCPRJ schema extensions

### PR DESCRIPTION
**Pull request by brondani**
Discussion: see issue https://github.com/Open-CMSIS-Pack/devtools/issues/171

### CODE REVIEW

**Comment by VGRSTM** [comment]
Sounds to me x2 evolutions are promoted here as part of same PR.
First is related to multiple cprj introduction see https://github.com/Open-CMSIS-Pack/devtools/issues/171
Second is adding common toolchain settings (optimize, warning, ... enum addon) see discussion if https://github.com/Open-CMSIS-Pack/devtools/issues/120

Myself would be happy to get such PR splitted in sync. not sure we are going to converge same speed on the two topics. I'm still doubtful about second one see related discussion.

**Comment by brondani** [comment]
> Myself would be happy to get such PR splitted in sync.

Agreed, splitted into separated PR: https://github.com/Open-CMSIS-Pack/devtools/pull/183

**Comment by tarek-bochkati** [comment]
just passing by (no real comment on the content)
just I thought that CPRJ schema (minor or patch) version should be incremented.

**Comment by tarek-bochkati** [comment]
just passing by (no real comment on the content)
just I thought that CPRJ schema (minor or patch) version should be incremented.

**Comment by brondani** [comment]
CPRJ will be deprecated, see https://github.com/Open-CMSIS-Pack/devtools/issues/171.

**Pull request closed without merging**
