### PR TITLE
[csolution] [cbuild] directory tree gets difficult to use.

### PR DESCRIPTION
**Pull request by VGRSTM**
Add capability to define custom output directories.

### CODE REVIEW

**Comment by VGRSTM** [comment]
Address https://github.com/Open-CMSIS-Pack/devtools/issues/221 schema part

**Comment by jkrech** [comment]
I think it is not wise to include 'rtedir' here. From my perspective the content of today's 'RTE' directory is part of the project source (it always needs to be committed to revision control system).
The other directories specify (reproducible) build information, intermediate build output and build artifacts.
In the context of layer handling as well depending on whether we plan to support multiple cprojects per single directory, we may need further review of the RTE directory.

**Comment by VGRSTM** [comment]
@jkrech not sure to understand your trouble here if RTE

Default can be:
> output-dirs:
 >   rtedir: ./RTE
 
 Renaming `RTE` folder is part already of [Allow the "RTE" folder name to be configurable](https://github.com/Open-CMSIS-Pack/devtools/pull/65). Such contribution was handling `cprj` only. Now we have `yml` so just promoting same here.

**Comment by ReinhardKeil** [comment]
Maybe we can extend this https://github.com/Open-CMSIS-Pack/devtools/issues/314#issuecomment-1118243602

**Review by brondani — APPROVED** [review]

**Comment by VGRSTM** [comment]
@brondani Thanks for such contribution !
I've got a try relying on some local build. Works as expected on my local example project. I've been got thru project manager and build manager workflow with some success.

image

I'm getting as expected new defaults in sync. #314 
Only comment is `cproject.yml` `output-dirs` settings if some are not applied per my trials.

**Comment by brondani** [comment]
> Only comment is cproject.yml output-dirs settings if some are not applied per my trials.

Thanks for the feedback @VGRSTM
As I commented [here](https://github.com/Open-CMSIS-Pack/devtools/issues/314#issuecomment-1174862661) it is purposely implemented only at csolution level, so it is not handled yet in `cproject.yml`. Let's get it consolidated before extending it.

**Pull request merged**
