### PR TITLE
ProfileType addon - devtools issue #179

### PR DESCRIPTION
**Pull request by VGRSTM**
Serving [comment](https://github.com/Open-CMSIS-Pack/devtools/issues/179#issuecomment-1193667376) if  [[projmgr] [buildmgr] Opportunity to introduce toolchain-independent configuration using the most common generic configurations](https://github.com/Open-CMSIS-Pack/devtools/issues/179)

### CODE REVIEW

**Review by ReinhardKeil — COMMENTED** [review]
I think this pull request is somewhat outdated as Tarek was working on that.

**Comment by VGRSTM** [comment]
> I think this pull request is somewhat outdated as Tarek was working on that.

Yes and no ... such `ProfileType` proposal is a way to get rid or addition possibly of toolchain abstractions supported today by `OptimizeType`, `DebugType`, `WarningType`. My 2 cents were and are I'm a bit doubtful today abstraction is going to be valuable enough. Having "only" boolean if  `DebugType`, `WarningType` and very limited flexibility if `OptimizeType` sounds fine if basic / common usage but.

**Comment by jkrech** [comment]
@VGRSTM I would like to suggest to close this PR for now and work with the proposed separate controls
`debug`, `optimize`, `warning`
We should review the usage in the examples to see whether used patterns could be expressed more effectively with profiles.

**Comment by ReinhardKeil** [comment]
@VGRSTM since the tool agnostic controls are working, is this pull request still needed?  I think it landed somewhat different?

**Comment by VGRSTM** [comment]
> @VGRSTM since the tool agnostic controls are working, is this pull request still needed? I think it landed somewhat different?

Let's close for now. If at a time we come back to https://github.com/Open-CMSIS-Pack/devtools/pull/415#issuecomment-1243495874 we will have opportunity to find this material back.

**Pull request closed without merging**
