### PR TITLE
PackChk: Changed M377 from INFO to WARNING

### PR DESCRIPTION
**Pull request by grasci-arm**
Fixes Open-CMSIS-Pack/devtools#139

### CODE REVIEW

**Review by jeromecoutant — APPROVED** [review]
You don't remove LEVEL_WARNING3 definition ?

**Comment by thorstendb-ARM** [comment]
> You don't remove LEVEL_WARNING3 definition ?

Can you please explain?
M377 has been changed from INFO to WARNING, as requested.

**Review by JonatanAntoni — APPROVED** [review]

**Comment by jeromecoutant** [comment]
> > You don't remove LEVEL_WARNING3 definition ?
> 
> @jeromecoutant , can you please explain? M377 has been changed from INFO to WARNING, as requested.

Just a  question :-)
What's the goal of so many warning levels ?
  m_msgLevelTable[MsgLevel::LEVEL_WARNING3] = "INFO";
  m_msgLevelTable[MsgLevel::LEVEL_WARNING2] = "WARNING";
  m_msgLevelTable[MsgLevel::LEVEL_WARNING]  = "WARNING";

**Comment by thorstendb-ARM** [comment]
> > > You don't remove LEVEL_WARNING3 definition ?
> > 
> > 
> > @jeromecoutant , can you please explain? M377 has been changed from INFO to WARNING, as requested.
> 
> Just a question :-) What's the goal of so many warning levels ? m_msgLevelTable[MsgLevel::LEVEL_WARNING3] = "INFO"; m_msgLevelTable[MsgLevel::LEVEL_WARNING2] = "WARNING"; m_msgLevelTable[MsgLevel::LEVEL_WARNING] = "WARNING";

Some could possibly be removed. Plan in the beginning of ErrLog for SVD was to have generic descending warning level scheme (see "enum class MsgLevel"), some of them can be filtered using -w<n>, others appear on "verbose". The implementation did not need some of them.
This shouldn't be an issue.

**Pull request merged**
