### PR TITLE
C and C++ linker flags support addon - devtools issue #224

### PR DESCRIPTION
**Pull request by VGRSTM**
Serving https://github.com/Open-CMSIS-Pack/devtools/issues/224

### CODE REVIEW

**Comment by VGRSTM** [comment]
@brondani  not sure to understand why ACI is failing here ... ?

**Comment by brondani** [comment]
> @brondani not sure to understand why ACI is failing here ... ?

Test projects containing the `Link` keyword are failing because this PR is removing it from the schema.
For example here: https://github.com/Open-CMSIS-Pack/devtools/runs/6211054212?check_suite_focus=true#step:5:572

**Comment by jkrech** [comment]
This is a backward incompatible change which would require to also include the source code changes in the tools as well as the changes in the tests as part of this pull request.
Can we consider a backward compatible change and deprecate the Link over time to not force examples to change immediately.

**Comment by VGRSTM** [comment]
Ok my bad have not looked at details per OSes log is more explicit for sure.
I've got issue now. Thanks.

>This is a backward incompatible change

I agree so. We come back to past discussion about e/o May toolbox tag will it be 1.0.0 or 0.x.y ... sounds to me too early to promote 1.0.0 ... 0.x.y allows according to me backward compatibility breaks ...

**Comment by ReinhardKeil** [comment]
Just to clearify expectations for May:  we want a stable release, but qualified as beta (V0.xx).  Currently it is alpha.  Beta does not give any backwards compatiblity.  V1.0 would do that - which I don't think we will reach until end of May.

**Comment by VGRSTM** [comment]
@ReinhardKeil I'm perfectly fine with and better to get it clearly stated. Thanks for that.

@jkrech I foresee so no issue to 
>force examples to change immediately

Still @jkrech  my pain is I cannot commit shortly having bandwidth / capability to propagate such update to tools & test non regression suites despite I perfectly acknowledge your request here.

**Comment by ReinhardKeil** [comment]
@VGRSTM this is quite old.  Is it still relevant?

**Comment by VGRSTM** [comment]
@ReinhardKeil 
> @VGRSTM this is quite old. Is it still relevant?

Yes it is. According to me no update since related to this area. We still have need to explicit variations if link process depending if C or Cpp project.

**Comment by ReinhardKeil** [comment]
Should be now covered under [misc](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#misc) with Link-C: and Link-CPP:

**Comment by brondani** [comment]
This has been implemented in the PR https://github.com/Open-CMSIS-Pack/devtools/pull/492

**Pull request closed without merging**
