### PR TITLE
Update and rename AC6.6.18.0.cmake to AC6.6.16.2.cmake

### PR DESCRIPTION
**Pull request by jkrech**
Arm Compiler 6.16.2 is a long term maintenance version of the Arm Compiler 6 and shall be supported by CMSIS-Toolbox as well. The cmake supports CPUs that are not supported by the 6.16.2 compiler version. For these CPUs the compiler will report an error on invocation.

### CODE REVIEW

**Review by brondani — CHANGES_REQUESTED** [review]
Further changes are required in scripts and tests, for example:
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/cbuildgen/installer/install.sh#L335
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/test/integrationtests/src/CBuildIntegTestEnv.cpp#L64
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/test/integrationtests/src/DebPkgTests.cpp#L51
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/test/integrationtests/src/DebPkgTests.cpp#L67
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/test/integrationtests/src/InstallerTests.cpp#L50
- https://github.com/Open-CMSIS-Pack/devtools/blob/jkrech-patch-2/tools/buildmgr/test/integrationtests/src/InstallerTests.cpp#L81
 
As well as in `cmsis-toolbox`:
- https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/scripts/set-default.sh#L21
- https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/test/tests.py#L20

**Review by brondani — APPROVED** [review]
LGTM

**Comment by brondani** [comment]
> [Open-CMSIS-Pack/cmsis-toolbox#123](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/pull/123) depends on this PR being merged first.

Please note that depends not only on this PR being merged but also on `buildmgr` being released and the toolbox workflow being updated accordingly.

**Comment by jkrech** [comment]
Thanks a lot for clarifying.

**Pull request merged**
